export const WorktreeErrorCode = {
  REPO_NOT_FOUND: 'WORKTREE_REPO_NOT_FOUND',
  CAPABILITY_MISSING: 'WORKTREE_CAPABILITY_MISSING',
  NAME_REQUIRED: 'WORKTREE_NAME_REQUIRED',
  NOT_FOUND: 'WORKTREE_NOT_FOUND',
  NOT_REGISTERED: 'WORKTREE_NOT_REGISTERED',
  PATH_CONFLICT: 'WORKTREE_PATH_CONFLICT',
  FORCE_REQUIRED: 'WORKTREE_FORCE_REQUIRED',
} as const;

export type WorktreeErrorCode = (typeof WorktreeErrorCode)[keyof typeof WorktreeErrorCode];
