export {
  computeContentHash,
  detectManagedRuleNamespace,
  detectOfficialWorkspaceFiles,
  detectRuleLayer,
  listVendorSkills,
  readManifestSkills,
  readRulesManifest,
  resolveAiAssets,
  rulesManifestPath,
  writeRulesManifest,
  writeVendorManifest,
  type AiAssets,
  type AiRulesManifest,
  type AiRulesManifestRule,
  type LocalModificationPolicy,
  type ManagedRuleNamespace,
  type RuleLayer,
} from '../../core/runtime/ai-manifest.js';
