import path from 'node:path';
import {createHash} from 'node:crypto';
import {fileURLToPath} from 'node:url';

import fs from 'fs-extra';

export type ManagedRuleNamespace = 'ldev' | 'ldev-workspace' | 'ldev-native';

export type RuleLayer = 'ldev-common' | 'project-type';

export type LocalModificationPolicy = 'replace-if-unmodified' | 'never-replace' | 'report-drift';

export type AiAssets = {
  repoRoot: string;
  packageVersion: string;
  aiRoot: string;
  installDir: string;
  projectDir: string;
  workspaceRulesSourceDir: string;
  vendorSkillsManifestPath: string;
  skillsSourceDir: string;
  agentsTemplatePath: string;
  workspaceAgentsTemplatePath: string;
};

export type AiRulesManifest = {
  version: 1;
  generatedAt: string;
  packageVersion: string;
  projectType: string;
  officialWorkspaceFilesDetected: string[];
  rules: AiRulesManifestRule[];
};

export type AiRulesManifestRule = {
  id: string;
  namespace: ManagedRuleNamespace;
  layer: RuleLayer;
  maintainer: 'ldev';
  sourceKind: 'custom' | 'derived';
  sourcePath: string;
  sourceReferences?: string[];
  targetFiles: string[];
  contentHash: string;
  verifiedAgainst: string[];
  lastVerifiedAt: string;
  verificationStatus: 'verified';
  verificationNotes?: string;
  localModificationPolicy: LocalModificationPolicy;
};

export function resolveAiAssets(repoRoot = getDefaultRepoRoot()): AiAssets {
  const aiRoot = path.join(repoRoot, 'templates', 'ai');
  const installDir = path.join(aiRoot, 'install');
  const projectDir = path.join(aiRoot, 'project');
  const workspaceRulesSourceDir = path.join(aiRoot, 'workspace-rules');
  const packageJson = fs.readJsonSync(path.join(repoRoot, 'package.json')) as {version?: string};

  return {
    repoRoot,
    packageVersion: packageJson.version ?? '0.0.0',
    aiRoot,
    installDir,
    projectDir,
    workspaceRulesSourceDir,
    vendorSkillsManifestPath: path.join(installDir, 'vendor-skills.txt'),
    skillsSourceDir: path.join(aiRoot, 'skills'),
    agentsTemplatePath: path.join(installDir, 'AGENTS.md'),
    workspaceAgentsTemplatePath: path.join(installDir, 'AGENTS.workspace.md'),
  };
}

export async function listVendorSkills(assets: AiAssets): Promise<string[]> {
  const content = await fs.readFile(assets.vendorSkillsManifestPath, 'utf8');
  return content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'))
    .sort();
}

export async function readManifestSkills(manifestPath: string): Promise<string[]> {
  if (!(await fs.pathExists(manifestPath))) {
    return [];
  }

  const content = await fs.readFile(manifestPath, 'utf8');
  return content
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));
}

export async function writeVendorManifest(manifestPath: string, skills: string[], generatedAt: Date): Promise<void> {
  const lines = [
    '# Skills installed by ldev',
    `# Updated: ${generatedAt.toISOString()}`,
    '# Do not edit manually — generated by ldev ai',
    ...skills,
    '',
  ];

  await fs.ensureDir(path.dirname(manifestPath));
  await fs.writeFile(manifestPath, lines.join('\n'));
}

export function rulesManifestPath(targetDir: string): string {
  return path.join(targetDir, '.ldev', 'ai', 'rules-manifest.json');
}

export async function writeRulesManifest(manifestPath: string, manifest: AiRulesManifest): Promise<void> {
  await fs.ensureDir(path.dirname(manifestPath));
  await fs.writeJson(manifestPath, manifest, {spaces: 2});
}

export async function readRulesManifest(manifestPath: string): Promise<AiRulesManifest | null> {
  if (!(await fs.pathExists(manifestPath))) {
    return null;
  }

  return (await fs.readJson(manifestPath)) as AiRulesManifest;
}

export function computeContentHash(content: string): string {
  return `sha256:${createHash('sha256').update(content).digest('hex')}`;
}

export function detectManagedRuleNamespace(baseName: string): ManagedRuleNamespace | null {
  if (baseName.startsWith('ldev-workspace-')) {
    return 'ldev-workspace';
  }
  if (baseName.startsWith('ldev-native-')) {
    return 'ldev-native';
  }
  if (baseName.startsWith('ldev-')) {
    return 'ldev';
  }
  return null;
}

export function detectRuleLayer(namespace: ManagedRuleNamespace): RuleLayer {
  return namespace === 'ldev' ? 'ldev-common' : 'project-type';
}

export async function detectOfficialWorkspaceFiles(targetDir: string): Promise<string[]> {
  const candidates = ['.workspace-rules/liferay-rules.md', '.claude/CLAUDE.md', '.github/copilot-instructions.md'];

  const detected: string[] = [];
  for (const relativePath of candidates) {
    if (await fs.pathExists(path.join(targetDir, relativePath))) {
      detected.push(relativePath);
    }
  }

  return detected;
}

function getDefaultRepoRoot(): string {
  return findPackageRoot(fileURLToPath(import.meta.url));
}

function findPackageRoot(fromFile: string): string {
  let current = path.dirname(fromFile);

  while (true) {
    if (fs.existsSync(path.join(current, 'package.json')) && fs.existsSync(path.join(current, 'templates', 'ai'))) {
      return current;
    }

    const parent = path.dirname(current);
    if (parent === current) {
      throw new Error(`Could not resolve the ldev package root from ${fromFile}`);
    }
    current = parent;
  }
}
